functionsDirectory = "/tmp/parking-ac-website-original/netlify/functions"
functionsDirectoryOrigin = "default"
redirectsOrigin = "config"
plugins = []
headers = []

[build]
publish = "/tmp/parking-ac-website-original/dist/client"
publishOrigin = "config"
commandOrigin = "config"
command = "npm install --legacy-peer-deps && npm run build"
functions = "/tmp/parking-ac-website-original/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]