mindmap
  root((CoolDrivePro<br/>Hub-and-Spoke))
    H1[H1 Truck Sleeper]
      H1-c02[long haul truck ac<br/>vol≈550, kw=1]
      H1-c03[truck sleeper ac reviews<br/>vol≈550, kw=1]
    H2[H2 RV / Motorhome]
      H2-c01[parking ac oem<br/>vol≈38945, kw=67]
      H2-c05[low profile rv ac<br/>vol≈1100, kw=2]
      H2-c06[rv ac power consumption<br/>vol≈550, kw=1]
    H3[H3 Van / Camper]
      H3-c09[promaster ac for camper<br/>vol≈550, kw=1]
    H4[H4 Battery / Solar]
      H4-c10[lifepo4 truck ac<br/>vol≈1380, kw=2]
      H4-c12[solar powered rv ac<br/>vol≈550, kw=1]
      H4-c14[inverter for rv ac<br/>vol≈550, kw=1]
      H4-c07[rv ac battery how long<br/>vol≈350, kw=2]
      H4-c11[battery powered ac for sleeping<br/>vol≈280, kw=1]
      H4-c13[solar panel for parking ac<br/>vol≈280, kw=1]
      H4-c15[how long can battery run ac<br/>vol≈140, kw=1]
    H5[H5 Anti-Idle & Fleet]
      H5-c17[no idle ordinance<br/>vol≈2210, kw=4]
      H5-c16[anti idling law california<br/>vol≈550, kw=1]
      H5-c18[fleet anti idling solutions<br/>vol≈550, kw=1]
      H5-c19[carb smartway approved ac<br/>vol≈550, kw=1]
      H5-c21[truck idle reduction technology<br/>vol≈550, kw=1]
      H5-c23[epa smartway parking ac<br/>vol≈550, kw=1]
      H5-c24[idle reduction grant 2026<br/>vol≈550, kw=1]
      H5-c20[fleet fuel savings no idle<br/>vol≈280, kw=1]
      H5-c22[apu return on investment trucking<br/>vol≈280, kw=1]
    H6[H6 Comparison]
      H6-c26[webasto alternative<br/>vol≈4400, kw=3]
      H6-c29[dometic alternative<br/>vol≈2915, kw=2]
      H6-c27[tripac alternative<br/>vol≈2270, kw=2]
      H6-c33[kingclima vs guchen<br/>vol≈2200, kw=2]
      H6-c04[apu vs battery ac<br/>vol≈1380, kw=3]
      H6-c30[indel b alternative<br/>vol≈1100, kw=1]
      H6-c31[truma ac alternative<br/>vol≈1100, kw=1]
      H6-c32[parking ac manufacturer comparison<br/>vol≈715, kw=1]
      H6-c28[rigmaster vs bergstrom nite<br/>vol≈550, kw=1]
      H6-c73[parking ac alibaba alternative<br/>vol≈550, kw=1]
      H6-c77[parking ac vs idle<br/>vol≈550, kw=1]
      H6-c25[dometic vs webasto parking ac<br/>vol≈280, kw=1]
      H6-c78[r134a vs r1234yf parking ac<br/>vol≈280, kw=1]
    H7[H7 Install & Fit]
      H7-c37[parking ac minimum roof thickness<br/>vol≈560, kw=2]
      H7-c08[transit van ac install<br/>vol≈550, kw=1]
      H7-c35[parking ac install cost<br/>vol≈550, kw=1]
      H7-c41[parking ac mounting bracket<br/>vol≈550, kw=1]
      H7-c42[parking ac install kit<br/>vol≈550, kw=1]
      H7-c43[parking ac wiring diagram<br/>vol≈550, kw=1]
      H7-c44[parking ac wiring kit<br/>vol≈550, kw=1]
      H7-c39[parking ac install diy<br/>vol≈385, kw=1]
      H7-c34[roof cutout size parking ac<br/>vol≈280, kw=1]
      H7-c36[install rooftop ac on truck<br/>vol≈280, kw=1]
      H7-c45[rooftop ac fits which trucks<br/>vol≈280, kw=1]
      H7-c38[best place to install parking ac<br/>vol≈182, kw=1]
      H7-c40[can i install parking ac myself<br/>vol≈98, kw=1]
    H8[H8 Regional Guides]
      H8-c46[parking ac mexico<br/>vol≈3300, kw=3]
      H8-c47[parking ac uk<br/>vol≈1100, kw=1]
      H8-c49[parking ac uae<br/>vol≈1100, kw=1]
      H8-c50[parking ac canada<br/>vol≈1100, kw=1]
      H8-c52[parking ac italy<br/>vol≈1100, kw=1]
      H8-c53[parking ac spain<br/>vol≈1100, kw=1]
      H8-c54[parking ac poland<br/>vol≈1100, kw=1]
      H8-c55[parking ac netherlands<br/>vol≈1100, kw=1]
      H8-c56[parking ac sweden<br/>vol≈1100, kw=1]
      H8-c57[parking ac russia<br/>vol≈1100, kw=1]
      H8-c58[parking ac thailand<br/>vol≈1100, kw=1]
      H8-c59[parking ac indonesia<br/>vol≈1100, kw=1]
      H8-c60[parking ac japan<br/>vol≈1100, kw=1]
      H8-c61[parking ac korea<br/>vol≈1100, kw=1]
      H8-c48[parking ac saudi arabia<br/>vol≈550, kw=1]
      H8-c51[parking ac south africa<br/>vol≈550, kw=1]
      H8-c62[parking ac new zealand<br/>vol≈550, kw=1]
    H9[H9 OEM / Wholesale]
      H9-c64[b2b parking ac supplier<br/>vol≈5225, kw=7]
      H9-c66[parking ac private label manufacturer<br/>vol≈914, kw=2]
      H9-c63[parking ac manufacturer china<br/>vol≈715, kw=1]
      H9-c67[oem truck ac manufacturer<br/>vol≈715, kw=1]
      H9-c72[parking ac supplier verification<br/>vol≈715, kw=1]
      H9-c65[parking ac distributor program<br/>vol≈550, kw=1]
      H9-c68[parking ac factory direct<br/>vol≈550, kw=1]
      H9-c69[parking ac upfitter program<br/>vol≈550, kw=1]
      H9-c70[parking ac distributor application<br/>vol≈550, kw=1]
      H9-c75[parking ac trade buyer<br/>vol≈550, kw=1]
      H9-c76[parking ac white label<br/>vol≈550, kw=1]
      H9-c79[parking ac oem customization<br/>vol≈550, kw=1]
      H9-c74[fleet parking ac bulk pricing<br/>vol≈280, kw=1]
      H9-c71[how to become parking ac distributor<br/>vol≈140, kw=1]